load('config.js');

function execute() {
    return Response.success([
        {title: "Tiên Hiệp", input: BASE_URL + "/theloai/tien-hiep/", script: "gen.js"},
        {title: "Kiếm Hiệp", input: BASE_URL + "/theloai/kiem-hiep/", script: "gen.js"},
        {title: "Ngôn Tình", input: BASE_URL + "/theloai/ngon-tinh/", script: "gen.js"},
        {title: "Đam Mỹ", input: BASE_URL + "/theloai/dam-my/", script: "gen.js"},
        {title: "Bách Hợp", input: BASE_URL + "/theloai/bach-hop/", script: "gen.js"},
        {title: "Đô Thị", input: BASE_URL + "/theloai/do-thi/", script: "gen.js"},
        {title: "Quan Trường", input: BASE_URL + "/theloai/quan-truong/", script: "gen.js"},
        {title: "Võng Du", input: BASE_URL + "/theloai/vong-du/", script: "gen.js"},
        {title: "Khoa Huyễn", input: BASE_URL + "/theloai/khoa-huyen/", script: "gen.js"},
        {title: "Hệ Thống", input: BASE_URL + "/theloai/he-thong/", script: "gen.js"},
        {title: "Huyền Huyễn", input: BASE_URL + "/theloai/huyen-huyen/", script: "gen.js"},
        {title: "Dị Giới", input: BASE_URL + "/theloai/di-gioi/", script: "gen.js"},
        {title: "Dị Năng", input: BASE_URL + "/theloai/di-nang/", script: "gen.js"},
        {title: "Quân Sự", input: BASE_URL + "/theloai/quan-su/", script: "gen.js"},
        {title: "Lịch Sử", input: BASE_URL + "/theloai/lich-su/", script: "gen.js"},
        {title: "Xuyên Không", input: BASE_URL + "/theloai/xuyen-khong/", script: "gen.js"},
        {title: "Xuyên Nhanh", input: BASE_URL + "/theloai/xuyen-nhanh/", script: "gen.js"},
        {title: "Trọng Sinh", input: BASE_URL + "/theloai/trong-sinh/", script: "gen.js"},
        {title: "Trinh Thám", input: BASE_URL + "/theloai/trinh-tham/", script: "gen.js"},
        {title: "Linh Dị", input: BASE_URL + "/theloai/linh-di/", script: "gen.js"},
        {title: "Ngược", input: BASE_URL + "/theloai/nguoc/", script: "gen.js"},
        {title: "Sắc", input: BASE_URL + "/theloai/sac/", script: "gen.js"},
        {title: "Sủng", input: BASE_URL + "/theloai/sung/", script: "gen.js"},
        {title: "Cung Đấu", input: BASE_URL + "/theloai/cung-dau/", script: "gen.js"},
        {title: "Nữ Cường", input: BASE_URL + "/theloai/nu-cuong/", script: "gen.js"},
        {title: "Gia Đấu", input: BASE_URL + "/theloai/gia-dau/", script: "gen.js"},
        {title: "Tổng Tài", input: BASE_URL + "/theloai/tong-tai/", script: "gen.js"},
        {title: "Đông Phương", input: BASE_URL + "/theloai/dong-phuong/", script: "gen.js"},
        {title: "Hài Hước", input: BASE_URL + "/theloai/hai-huoc/", script: "gen.js"},
        {title: "Điền Văn", input: BASE_URL + "/theloai/dien-van/", script: "gen.js"},
        {title: "Truyện Teen", input: BASE_URL + "/theloai/truyen-teen/", script: "gen.js"},
        {title: "Mạt Thế", input: BASE_URL + "/theloai/mat-the/", script: "gen.js"},
        {title: "Cổ Đại", input: BASE_URL + "/theloai/co-dai/", script: "gen.js"},
        {title: "Phương Tây", input: BASE_URL + "/theloai/phuong-tay/", script: "gen.js"},
        {title: "Nữ Phụ", input: BASE_URL + "/theloai/nu-phu/", script: "gen.js"},
        {title: "Light Novel", input: BASE_URL + "/theloai/light-novel/", script: "gen.js"},
        {title: "Đoản Văn", input: BASE_URL + "/theloai/doan-van/", script: "gen.js"},
        {title: "Thám Hiểm", input: BASE_URL + "/theloai/tham-hiem/", script: "gen.js"},
        {title: "Việt Nam", input: BASE_URL + "/theloai/viet-nam/", script: "gen.js"},
        {title: "Hiện Đại", input: BASE_URL + "/theloai/Hien-Dai/", script: "gen.js"},
        {title: "Khác", input: BASE_URL + "/theloai/khac/", script: "gen.js"}
    ]);
}
